### ISSUE TITLE
Incorporate new copy for direct signing page

### ISSUE THREAD

**Issue by aypei** [leather-io/lockstacks#176]
Here is the new copy for the direct signing page, both in [this doc](https://docs.google.com/document/d/144TqZm5M1nVRHyma-5rgoc0GFoOWY6LJLHWJiHFDRMA/edit) for reference, and pasted here as well: 

**Signer Information**

When you engage in Stacking, you’re associating your locked STX with a signer actively involved in the Stacks network’s consensus process. With the [Nakamoto Release](https://www.nakamoto.run/), Stackers who choose to stack independently will need to run their own signer software. 

If you’re interested in running your own signer, please consult [these documents](https://docs.stacks.co/nakamoto-upgrade/signing-and-stacking/stacking-flow) on how to Stack as a signer and fill out [this page](https://staging.lockstacks.com/signer/generate-signature?chain=mainnet) to generate a signer signature. If you prefer not to manage your own signer, we suggest [Stacking using another method](https://staging.lockstacks.com/start-pooled-stacking). 

Users who are not running their own signer software will need to request this data from the signer that you’re using. Enter the data you receive here:

[bulk signer data]

**Signer Public Key**
Enter the signer’s public key in hexadecimal format:

**Signer Signature (optional)**
Enter the hexadecimal signature from the signer enabling you to Stack with their key. Leave this field blank if the signature is universal for all Stackers who use this signer:

**Max Amount**
Enter the maximum amount of STX that can be locked while using this signature:

**Auth ID**
Enter the signer’s Auth ID, a randomly generated number that prevents signer signature reuse:

**Comment by renashah** [comment]
Hi! Can I request a tiny copy update to this page to include the Degen Labs option to run a signer? It's listed in the same documentation we use from Stacks Foundation. An update would only be in the Signer Information section. 


NEW:

Signer Information

When you engage in Stacking, you’re associating your locked STX with a signer actively involved in the Stacks network’s consensus process. With the [Nakamoto Release](https://www.nakamoto.run/), Stackers who choose to stack independently will need to run their own signer software. There is a dapp created by DegenLabs for [independent stacking](https://solo.stacking.tools/) without needing a signer, as DegenLabs operates a signer.

If you’re interested in running your own signer, please consult [these documents](https://docs.stacks.co/nakamoto-upgrade/signing-and-stacking/stacking-flow) on how to Stack as a signer and fill out [this page](https://staging.lockstacks.com/signer/generate-signature?chain=mainnet) to generate a signer signature.  


Appreciate it @friedger 
Tagging for visibility @markmhendrickson @aypei @fabric-8

**Comment by renashah** [comment]
Yep! that works

**Comment by fabric-8** [comment]
Note: All copy changes have been incorporated into leather earn
